import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

/**This file is autoGenerated by TailwindCss and should not be changed without knowing exactly what is being done. */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
